import { BaseEntity } from '../types/common';

export interface CreateVideoDto {
  class: string;
  api_id?: string;
  date_created?: Date;
  deleted?: boolean;
  imdb_id?: string;
  intro_end?: number;
  intro_start?: number;
  last_updated?: Date;
  original_language?: string;
  outro_start?: number;
  overview?: string;
  popularity?: number;
  report_count?: number;
  vote_average?: number;
  vote_count?: number;
  backdrop_path?: string;
  poster_image_id?: string | null;
  poster_path?: string;
  release_date?: string;
  title?: string;
  trailer_key?: string;
  backdrop_image_id?: string | null;
  air_date?: string;
  episode_string?: string;
  episode_number?: number;
  name?: string;
  season_episode_merged?: number;
  season_number?: number;
  show_id?: string | null;
  still_image_id?: string | null;
  still_path?: string;
  duration?: string;
}

export interface UpdateVideoDto {
  class?: string;
  api_id?: string;
  last_updated?: Date;
  deleted?: boolean;
  imdb_id?: string;
  intro_end?: number;
  intro_start?: number;
  original_language?: string;
  outro_start?: number;
  overview?: string;
  popularity?: number;
  report_count?: number;
  vote_average?: number;
  vote_count?: number;
  backdrop_path?: string;
  poster_image_id?: string | null;
  poster_path?: string;
  release_date?: string;
  title?: string;
  trailer_key?: string;
  backdrop_image_id?: string | null;
  air_date?: string;
  episode_string?: string;
  episode_number?: number;
  name?: string;
  season_episode_merged?: number;
  season_number?: number;
  show_id?: string | null;
  still_image_id?: string | null;
  still_path?: string;
  duration?: string;
}

export interface VideoResponseDto extends BaseEntity {
  id: string;
  version?: number;
  api_id?: string;
  date_created?: string;
  deleted?: boolean;
  imdb_id?: string;
  intro_end?: number;
  intro_start?: number;
  last_updated?: string;
  original_language?: string;
  outro_start?: number;
  overview?: string;
  popularity?: number;
  report_count?: number;
  vote_average?: number;
  vote_count?: number;
  class: string;
  backdrop_path?: string;
  poster_image_id?: string | null;
  poster_path?: string;
  release_date?: string;
  title?: string;
  trailer_key?: string;
  backdrop_image_id?: string | null;
  air_date?: string;
  episode_string?: string;
  episode_number?: number;
  name?: string;
  season_episode_merged?: number;
  season_number?: number;
  show_id?: string | null;
  still_image_id?: string | null;
  still_path?: string;
  duration?: string;
}