export class CreateInstitutionsDto {
  version?: string = "";
  accountableContact?: string = "";
  accountableName?: string = "";
  companyName?: string = "";
  complement?: string = "";
  contractDisabled?: string = "";
  contractInvoiceNum?: string = "";
  contractNum?: string = "";
  contractTermEnd?: string = "";
  contractTermStart?: string = "";
  deleted?: string = "";
  district?: string = "";
  document?: string = "";
  invoiceDate?: string = "";
  name?: string = "";
  postalCode?: string = "";
  state?: string = "";
  street?: string = "";
  score?: string = "";
  hasLibraryPlatform?: string = "";
  hasPrincipalPlatform?: string = "";
  hasStudentPlatform?: string = "";
  type?: string = "";
  status?: string = "";
}

export class UpdateInstitutionsDto {
  version?: string = "";
  accountableContact?: string = "";
  accountableName?: string = "";
  companyName?: string = "";
  complement?: string = "";
  contractDisabled?: string = "";
  contractInvoiceNum?: string = "";
  contractNum?: string = "";
  contractTermEnd?: string = "";
  contractTermStart?: string = "";
  deleted?: string = "";
  district?: string = "";
  document?: string = "";
  invoiceDate?: string = "";
  name?: string = "";
  postalCode?: string = "";
  state?: string = "";
  street?: string = "";
  score?: string = "";
  hasLibraryPlatform?: string = "";
  hasPrincipalPlatform?: string = "";
  hasStudentPlatform?: string = "";
  type?: string = "";
  status?: string = "";
}

export class InstitutionsResponseDto {
  id: string = "";
  version: string = "";
  accountableContact: string = "";
  accountableName: string = "";
  companyName: string = "";
  complement: string = "";
  contractDisabled: string = "";
  contractInvoiceNum: string = "";
  contractNum: string = "";
  contractTermEnd: string = "";
  contractTermStart: string = "";
  dateCreated: string = "";
  deleted: string = "";
  district: string = "";
  document: string = "";
  invoiceDate: string = "";
  lastUpdated: string = "";
  name: string = "";
  postalCode: string = "";
  state: string = "";
  street: string = "";
  score: string = "";
  hasLibraryPlatform: string = "";
  hasPrincipalPlatform: string = "";
  hasStudentPlatform: string = "";
  type: string = "";
  status: string = "";
  createdAt: string = "";
  updatedAt: string = "";
}