/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Limpar dados existentes
  await knex('tv_shows').del();
  
  // Inserir dados de coleções educacionais
  await knex('tv_shows').insert([
    {
      id: 1,
      title: 'Matemática Fundamental',
      description: 'Uma coleção completa de vídeos educacionais sobre matemática fundamental, cobrindo desde conceitos básicos até tópicos avançados. Ideal para estudantes do ensino fundamental e médio.',
      poster_url: 'https://via.placeholder.com/400x600/4A90E2/FFFFFF?text=Matemática+Fundamental',
      seasons: 3,
      episodes: 45,
      first_air_date: '2023-01-15',
      last_air_date: '2024-06-30',
      status: 'ongoing',
      genre_id: 1,
      target_audience_id: 1,
      language_id: 1,
      is_featured: true,
      is_active: true,
      view_count: 1250,
      rating: 4.8,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 2,
      title: 'Ciências da Natureza',
      description: 'Explore o fascinante mundo das ciências naturais através de experimentos práticos e explicações didáticas. Conteúdo alinhado com a BNCC para o ensino fundamental.',
      poster_url: 'https://via.placeholder.com/400x600/50C878/FFFFFF?text=Ciências+da+Natureza',
      seasons: 2,
      episodes: 32,
      first_air_date: '2023-03-20',
      last_air_date: '2024-05-15',
      status: 'ongoing',
      genre_id: 2,
      target_audience_id: 1,
      language_id: 1,
      is_featured: true,
      is_active: true,
      view_count: 980,
      rating: 4.6,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 3,
      title: 'História do Brasil',
      description: 'Uma jornada pela rica história do Brasil, desde o período colonial até os dias atuais. Narrativas envolventes com recursos visuais e documentários exclusivos.',
      poster_url: 'https://via.placeholder.com/400x600/FF6B6B/FFFFFF?text=História+do+Brasil',
      seasons: 4,
      episodes: 56,
      first_air_date: '2022-08-10',
      last_air_date: '2024-03-25',
      status: 'ongoing',
      genre_id: 3,
      target_audience_id: 2,
      language_id: 1,
      is_featured: true,
      is_active: true,
      view_count: 1520,
      rating: 4.9,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 4,
      title: 'Língua Portuguesa',
      description: 'Domine a língua portuguesa com lições interativas sobre gramática, literatura e redação. Conteúdo preparatório para vestibulares e ENEM.',
      poster_url: 'https://via.placeholder.com/400x600/9B59B6/FFFFFF?text=Língua+Portuguesa',
      seasons: 3,
      episodes: 42,
      first_air_date: '2023-02-01',
      last_air_date: '2024-07-10',
      status: 'ongoing',
      genre_id: 4,
      target_audience_id: 2,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 890,
      rating: 4.5,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 5,
      title: 'Física Experimental',
      description: 'Compreenda os princípios da física através de experimentos práticos e demonstrações visuais. Ideal para estudantes do ensino médio e pré-vestibular.',
      poster_url: 'https://via.placeholder.com/400x600/F39C12/FFFFFF?text=Física+Experimental',
      seasons: 2,
      episodes: 28,
      first_air_date: '2023-04-12',
      last_air_date: '2024-02-20',
      status: 'ongoing',
      genre_id: 2,
      target_audience_id: 2,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 675,
      rating: 4.7,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 6,
      title: 'Geografia Mundial',
      description: 'Explore os continentes, países e culturas do mundo através de mapas interativos e documentários. Conteúdo atualizado com dados geopolíticos recentes.',
      poster_url: 'https://via.placeholder.com/400x600/27AE60/FFFFFF?text=Geografia+Mundial',
      seasons: 3,
      episodes: 38,
      first_air_date: '2022-11-05',
      last_air_date: '2024-04-18',
      status: 'ongoing',
      genre_id: 3,
      target_audience_id: 1,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 1100,
      rating: 4.4,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 7,
      title: 'Química Orgânica',
      description: 'Desvende os mistérios da química orgânica com explicações claras sobre estruturas moleculares, reações e aplicações no cotidiano.',
      poster_url: 'https://via.placeholder.com/400x600/8E44AD/FFFFFF?text=Química+Orgânica',
      seasons: 2,
      episodes: 24,
      first_air_date: '2023-05-08',
      last_air_date: '2024-01-30',
      status: 'ended',
      genre_id: 2,
      target_audience_id: 2,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 580,
      rating: 4.6,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 8,
      title: 'Biologia Celular',
      description: 'Mergulhe no mundo microscópico das células e descubra os processos fundamentais da vida. Inclui animações 3D e microscopia avançada.',
      poster_url: 'https://via.placeholder.com/400x600/E74C3C/FFFFFF?text=Biologia+Celular',
      seasons: 1,
      episodes: 18,
      first_air_date: '2023-06-15',
      last_air_date: '2023-12-10',
      status: 'ended',
      genre_id: 2,
      target_audience_id: 2,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 720,
      rating: 4.8,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 9,
      title: 'Arte e Cultura Brasileira',
      description: 'Conheça a riqueza da arte e cultura brasileira através de documentários sobre artistas, movimentos artísticos e manifestações culturais regionais.',
      poster_url: 'https://via.placeholder.com/400x600/FF8C00/FFFFFF?text=Arte+e+Cultura',
      seasons: 2,
      episodes: 26,
      first_air_date: '2023-07-20',
      last_air_date: '2024-05-30',
      status: 'ongoing',
      genre_id: 5,
      target_audience_id: 1,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 450,
      rating: 4.3,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 10,
      title: 'Educação Financeira',
      description: 'Aprenda conceitos essenciais de educação financeira, desde planejamento pessoal até investimentos básicos. Conteúdo prático para jovens e adultos.',
      poster_url: 'https://via.placeholder.com/400x600/2ECC71/FFFFFF?text=Educação+Financeira',
      seasons: 1,
      episodes: 15,
      first_air_date: '2023-09-01',
      last_air_date: '2024-01-15',
      status: 'ended',
      genre_id: 6,
      target_audience_id: 3,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 320,
      rating: 4.2,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 11,
      title: 'Programação para Iniciantes',
      description: 'Introdução ao mundo da programação com linguagens como Python e JavaScript. Projetos práticos e exercícios interativos para desenvolver habilidades.',
      poster_url: 'https://via.placeholder.com/400x600/3498DB/FFFFFF?text=Programação',
      seasons: 2,
      episodes: 30,
      first_air_date: '2023-10-10',
      last_air_date: '2024-06-20',
      status: 'ongoing',
      genre_id: 7,
      target_audience_id: 2,
      language_id: 1,
      is_featured: true,
      is_active: true,
      view_count: 950,
      rating: 4.7,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      id: 12,
      title: 'Filosofia Contemporânea',
      description: 'Explore as principais correntes do pensamento filosófico contemporâneo através de debates e análises de textos fundamentais.',
      poster_url: 'https://via.placeholder.com/400x600/95A5A6/FFFFFF?text=Filosofia',
      seasons: 1,
      episodes: 20,
      first_air_date: '2023-11-15',
      last_air_date: '2024-04-10',
      status: 'ended',
      genre_id: 8,
      target_audience_id: 2,
      language_id: 1,
      is_featured: false,
      is_active: true,
      view_count: 380,
      rating: 4.1,
      created_at: new Date(),
      updated_at: new Date()
    }
  ]);
  
  console.log('✅ Seed tv_shows executado com sucesso - 12 coleções criadas');
}; 